language: java
sudo: required
python: 2.7
services:
  - cassandra
env:
  - TZ=UTC
install:
  - python -V
  - sudo pip install pytz # cqlsh need this package
script:
  - ./gradlew check
after_success:
  - ./gradlew coveralls --continue